# https://taskfile.dev

version: "3"

tasks:
  list-tables:
    cmds:
      - docker compose exec aws awslocal dynamodb list-tables

  setup:
    cmds:
      - docker compose exec aws npx cdklocal bootstrap

  deploy:
    cmds:
      - docker compose exec aws sh ./deploy.sh

  ses-verify:
    cmds:
      - docker compose exec aws awslocal ses verify-email-identity --email-address "sender@example.com"
      - docker compose exec aws awslocal ses verify-email-identity --email-address "receiver@example.com"

  ses-list:
    cmds:
      - docker compose exec aws awslocal ses list-identities
