# https://taskfile.dev

version: "3"

tasks:
  list-tables:
    cmds:
      - docker compose exec aws awslocal dynamodb list-tables

  bash:
    cmds:
      - docker compose exec aws bash

  setup:
    cmds:
      - docker compose exec aws npx cdklocal bootstrap

  setup-moto:
    cmds:
      - docker compose exec aws sh ./setup-moto.sh

  deploy:
    cmds:
      - docker compose exec aws sh ./deploy.sh

  deploy-moto:
    cmds:
      - docker compose exec aws sh ./deploy-moto.sh

  deploy-all:
    cmds:
      - task: deploy
      - task: deploy-moto

  watch:
    cmds:
      - docker compose exec aws npm run watch

  delete-lambda:
    cmds:
      - docker compose exec aws awslocal cloudformation delete-stack --stack-name LambdaStack

  apiid:
    cmds:
      - docker compose exec aws awslocal apigateway get-rest-apis --query "items[*].id"

  openapi:
    cmds:
      - sh ./openapi.sh

  setenv:
    cmds:
      - sh ./setenv.sh
